[PROJECT]
name = Avito
url = https://www.google.com/search?q=roblox+is+banned+in+russia&sca_esv=2a9cf1d07f23bfb1&source=hp&ei=rnwqauiRKPjVwPAP-cXLiQU&iflsig=AFdpzrgAAAAAaiqKvqxiWQo1fQ1rqETD-SXrsfgJ6d2h&oq=roblox+is+unbanned&gs_lp=Egdnd3Mtd2l6IhJyb2Jsb3ggaXMgdW5iYW5uZWQqAggAMgoQABiABBgNGMcDMgcQABiABBgNMgoQABiABBgNGMcDMgYQABgeGA0yBhAAGB4YDTIGEAAYHhgNMgYQABgeGA0yBhAAGB4YDTIGEAAYHhgNMgYQABgeGA1Ir0pQyxtYtjpwAXgAkAEAmAFSoAHRCKoBAjE4uAEDyAEA-AEBmAIToALbCagCCsICChAuGAMYjwEY6gLCAgoQABgDGI8BGOoCwgILEC4YgAQYsQMYgwHCAg4QLhiABBixAxjHARjRA8ICCBAAGIAEGLEDwgIFEC4YgATCAhEQLhiABBixAxiDARjHARjRA8ICDhAAGIAEGIoFGLEDGIMBwgIUEC4YgAQYsQMYgwEYxwEYrwEYjgXCAgsQABiABBixAxiDAcICBRAAGIAEwgIOEC4YxwEYsQMY0QMYgATCAhAQABiABBiKBRixAxiDARgKwgIEEAAYA8ICBhAAGBYYHsICCBAAGBYYHhgKmAMX8QVjM_EgNdXJcJIHAjE5oAfGgAGyBwIxOLgHxAnCBwgyLTE3LjEuMcgHaoAIAQ&sclient=gws-wiz

[BROWSER]
headless = true
timeout = 10
retry_count = 3

[URLS]
main = https://www.google.com/search?q=roblox+is+banned+in+russia&sca_esv=2a9cf1d07f23bfb1&source=hp&ei=rnwqauiRKPjVwPAP-cXLiQU&iflsig=AFdpzrgAAAAAaiqKvqxiWQo1fQ1rqETD-SXrsfgJ6d2h&oq=roblox+is+unbanned&gs_lp=Egdnd3Mtd2l6IhJyb2Jsb3ggaXMgdW5iYW5uZWQqAggAMgoQABiABBgNGMcDMgcQABiABBgNMgoQABiABBgNGMcDMgYQABgeGA0yBhAAGB4YDTIGEAAYHhgNMgYQABgeGA0yBhAAGB4YDTIGEAAYHhgNMgYQABgeGA1Ir0pQyxtYtjpwAXgAkAEAmAFSoAHRCKoBAjE4uAEDyAEA-AEBmAIToALbCagCCsICChAuGAMYjwEY6gLCAgoQABgDGI8BGOoCwgILEC4YgAQYsQMYgwHCAg4QLhiABBixAxjHARjRA8ICCBAAGIAEGLEDwgIFEC4YgATCAhEQLhiABBixAxiDARjHARjRA8ICDhAAGIAEGIoFGLEDGIMBwgIUEC4YgAQYsQMYgwEYxwEYrwEYjgXCAgsQABiABBixAxiDAcICBRAAGIAEwgIOEC4YxwEYsQMY0QMYgATCAhAQABiABBiKBRixAxiDARgKwgIEEAAYA8ICBhAAGBYYHsICCBAAGBYYHhgKmAMX8QVjM_EgNdXJcJIHAjE5oAfGgAGyBwIxOLgHxAnCBwgyLTE3LjEuMcgHaoAIAQ&sclient=gws-wiz

[VARIABLES]
items = []

[OUTPUT]
format = excel
excel_path = output.xlsx
json_path = output.json

[LOGGING]
level = INFO
log_file = parser.log

[TELEGRAM]
enabled = false
bot_token = 8534461995:AAECSgJhPayYkegD0u-e7j2Y0iPiD7-jBlY
chat_id = 
