#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# {NAME}Parser.py
# Generated by UPB - Universal Parser Builder
# Date: {DATE}

import time
import json
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from pathlib import Path

import pandas as pd
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException


# ========== КОНФИГУРАЦИЯ (вставляется из config.conf) ==========
CONFIG = {
    "parser": {
        "name": "{NAME}",
        "url": "{URL}",
        "headless": {HEADLESS},
        "timeout": {TIMEOUT},
        "wait_between_requests": {WAIT}
    },
    "output": {
        "format": "{OUTPUT_FORMAT}",
        "excel_path": "{EXCEL_PATH}",
        "json_path": "{JSON_PATH}"
    },
    "telegram": {
        "enabled": {TG_ENABLED},
        "bot_token": "{TG_BOT_TOKEN}",
        "chat_id": "{TG_CHAT_ID}"
    },
    "logging": {
        "level": "{LOG_LEVEL}",
        "log_file": "{LOG_FILE}"
    },
    "advanced": {
        "retry_count": {RETRY_COUNT},
        "screenshot_on_error": {SCREENSHOT_ON_ERROR}
    }
}

# ========== ПЕРЕМЕННЫЕ ИЗ VM ТАБЛИЦЫ (вставляются автоматически) ==========
VARIABLES = {
    # {VARIABLES_PLACEHOLDER}
    # Пример:
    # "title": {"xpath": "//h1", "type": "static"},
    # "price": {"xpath": "//span[@class='price']", "type": "dynamic"},
    # "api_data": {"url": "https://api.example.com/data", "type": "network"}
}

# ========== НАСТРОЙКА ЛОГИРОВАНИЯ ==========
def setup_logging():
    """Настраивает логирование"""
    log_level = getattr(logging, CONFIG["logging"]["level"].upper(), logging.INFO)
    logging.basicConfig(
        level=log_level,
        format='%(asctime)s | %(levelname)-8s | %(message)s',
        datefmt='%H:%M:%S',
        handlers=[
            logging.FileHandler(CONFIG["logging"]["log_file"], encoding='utf-8'),
            logging.StreamHandler()
        ]
    )
    return logging.getLogger(CONFIG["parser"]["name"])

logger = setup_logging()


# ========== КЛАСС ПАРСЕРА ==========
class UPBParser:
    """Универсальный парсер, сгенерированный UPB"""
    
    def __init__(self):
        self.driver = None
        self.wait = None
        self.results = {}
        
        # Настройки
        self.headless = CONFIG["parser"]["headless"]
        self.timeout = CONFIG["parser"]["timeout"]
        self.retry_count = CONFIG["advanced"]["retry_count"]
        self.screenshot_on_error = CONFIG["advanced"]["screenshot_on_error"]
        
        self._init_driver()
    
    def _init_driver(self):
        """Инициализация WebDriver"""
        options = webdriver.ChromeOptions()
        
        if self.headless:
            options.add_argument('--headless=new')
        
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        
        self.driver = webdriver.Chrome(options=options)
        self.driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
        
        self.wait = WebDriverWait(self.driver, self.timeout)
        logger.info(f"✅ Драйвер инициализирован (headless={self.headless})")
    
    def _get_static(self, xpath: str) -> Optional[str]:
        """Получение статического элемента по XPath"""
        try:
            element = self.wait.until(
                EC.presence_of_element_located((By.XPATH, xpath))
            )
            return element.text.strip() or element.get_attribute('innerHTML')
        except TimeoutException:
            logger.warning(f"⏰ Таймаут: элемент не найден - {xpath[:50]}...")
            return None
        except Exception as e:
            logger.error(f"❌ Ошибка при получении элемента: {e}")
            return None
    
    def _get_dynamic(self, xpath: str) -> Optional[str]:
        """Получение динамического элемента (с ожиданием видимости)"""
        try:
            element = self.wait.until(
                EC.visibility_of_element_located((By.XPATH, xpath))
            )
            return element.text.strip()
        except TimeoutException:
            logger.warning(f"⏰ Динамический элемент не появился - {xpath[:50]}...")
            return None
    
    def _get_network(self, url: str) -> Optional[Dict]:
        """Получение данных из network запроса"""
        try:
            response = requests.get(url, timeout=self.timeout)
            response.raise_for_status()
            return response.json()
        except Exception as e:
            logger.error(f"❌ Network запрос не удался: {e}")
            return None
    
    def _collect_data(self) -> Dict:
        """Сбор всех данных на основе VARIABLES"""
        results = {}
        
        logger.info(f"🚀 Начинаем сбор данных...")
        
        for name, meta in VARIABLES.items():
            logger.debug(f"📌 Обработка: {name} (тип: {meta.get('type', 'static')})")
            
            for attempt in range(self.retry_count):
                try:
                    if meta['type'] == 'static':
                        value = self._get_static(meta['xpath'])
                    elif meta['type'] == 'dynamic':
                        value = self._get_dynamic(meta['xpath'])
                    elif meta['type'] == 'network':
                        value = self._get_network(meta.get('url', ''))
                    else:
                        value = None
                    
                    if value:
                        results[name] = value
                        logger.info(f"   ✅ {name}: {str(value)[:50]}...")
                        break
                    else:
                        logger.warning(f"   ⚠️ {name}: попытка {attempt + 1}/{self.retry_count}")
                        time.sleep(CONFIG["parser"]["wait_between_requests"])
                        
                except Exception as e:
                    logger.error(f"   ❌ {name}: ошибка - {e}")
                    if self.screenshot_on_error:
                        self.driver.save_screenshot(f"error_{name}.png")
        
        return results
    
    def _export_excel(self):
        """Экспорт в Excel"""
        df = pd.DataFrame([self.results])
        df.to_excel(CONFIG["output"]["excel_path"], index=False)
        logger.info(f"📊 Экспорт в Excel: {CONFIG['output']['excel_path']}")
    
    def _export_json(self):
        """Экспорт в JSON"""
        with open(CONFIG["output"]["json_path"], 'w', encoding='utf-8') as f:
            json.dump(self.results, f, ensure_ascii=False, indent=2)
        logger.info(f"📄 Экспорт в JSON: {CONFIG['output']['json_path']}")
    
    def _send_telegram(self):
        """Отправка в Telegram"""
        if not CONFIG["telegram"]["enabled"]:
            return
        
        message = f"📊 *{CONFIG['parser']['name']}* - результаты парсинга\n\n"
        for key, value in self.results.items():
            message += f"• *{key}*: {str(value)[:100]}\n"
        
        url = f"https://api.telegram.org/bot{CONFIG['telegram']['bot_token']}/sendMessage"
        payload = {
            "chat_id": CONFIG["telegram"]["chat_id"],
            "text": message,
            "parse_mode": "Markdown"
        }
        
        try:
            response = requests.post(url, json=payload, timeout=10)
            if response.status_code == 200:
                logger.info("📨 Отправлено в Telegram")
            else:
                logger.error(f"❌ Ошибка Telegram: {response.text}")
        except Exception as e:
            logger.error(f"❌ Telegram ошибка: {e}")
    
    def run(self):
        """Основной метод запуска парсера"""
        try:
            logger.info(f"🌐 Загрузка страницы: {CONFIG['parser']['url']}")
            self.driver.get(CONFIG["parser"]["url"])
            time.sleep(2)  # Ждём первоначальную загрузку
            
            self.results = self._collect_data()
            
            # Экспорт результатов
            output_format = CONFIG["output"]["format"]
            
            if output_format in ['excel', 'all']:
                self._export_excel()
            if output_format in ['json', 'all']:
                self._export_json()
            
            self._send_telegram()
            
            logger.info(f"✅ Парсинг завершён! Собрано {len(self.results)} переменных")
            
        except Exception as e:
            logger.error(f"💥 Критическая ошибка: {e}")
            if self.screenshot_on_error:
                self.driver.save_screenshot("fatal_error.png")
            raise
        finally:
            self.close()
    
    def close(self):
        """Закрытие драйвера"""
        if self.driver:
            self.driver.quit()
            logger.info("🔒 Драйвер закрыт")


# ========== ТОЧКА ВХОДА ==========
def main():
    parser = UPBParser()
    parser.run()


if __name__ == "__main__":
    main()